font_size            13.0
include              seoul256.conf
font_family          Maple Mono
bold_font            auto
italic_font          auto
bold_italic_font     auto
window_padding_width 10


# BEGIN_KITTY_THEME
# Twilight
include current-theme.conf
# END_KITTY_THEME