#!/usr/bin/env bash

# --- GENERAL ---
# big limit (too big?)
set -g history-limit 50000
# automatic titles
set-window-option -g automatic-rename on
set-option -g set-titles on

set -g focus-events on

# --- INPUT ---
set -g mouse on
setw -g mode-keys vi

# alt-vim keys to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# alt-vim keys (caps) to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# custom binds for splitting
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"

bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

# no escape time for key press
set -sg escape-time 0

# reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# sane scrolling
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

# --- CLIPBOARD ---
set-option -s set-clipboard off
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"  # macOS

# Use system clipboard
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'

# --- UI ---
# dynamic number windows
set -g renumber-windows on

# customize status line
set -g status-position top
set -g status-style bg="#131313",fg="#f3f3f3"
set -g pane-border-style fg=coral
set -g status-left "#[bg=red] #S #[bg=#131313]  "
set -g status-right ""
set -g window-status-current-style "none"
set -g window-status-separator "  "
set -g window-status-format "#[fg=#656565]#W"
set -g window-status-current-format "#[fg=orange]• #[fg=white]#W"
set -g status-justify left
