#!/usr/bin/env bash
set -g mouse on

bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"

bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# customize status line
set -g status-position top
set -g status-style bg="#222222",fg="#f3f3f3"
set -g pane-border-style fg=coral
set -g status-left "#[bg=red] #S #[bg=black]  "
set -g status-right ""
set -g window-status-current-style "none"
set -g window-status-separator "  "
set -g window-status-format "#[fg=#656565]#W"
set -g window-status-current-format "#[fg=orange]• #[fg=white]#W"
set -g status-justify left
